### ISSUE TITLE
Database Builder-Export/Import Project

### ISSUE THREAD

**Issue by aekadinata** [alfanugraha/lumens_scripts#17]
Create algorithm to export/packaging and import LUMENS project database

**Comment by adwiputra** [comment]
Import done @alfanugraha pls check [33fe6a2](https://github.com/alfanugraha/lumens_scripts/commit/33fe6a2385b7fdf2b71891332a09304ad6cd2b7d)

**Comment by adwiputra** [comment]
Export done 308382fd
