### ISSUE TITLE
UI LUMENS

### ISSUE THREAD

**Issue by arizkamufida** [alfanugraha/lumens_scripts#38]
Mintol gan alfa:

1. Ganti warna font
2. Ubah ukuran font
3. Menu Bar langsung ditampilkan (tidak perlu press F11)
4. Menu Bar isinya hanya: File (isinya sama dengan yg sekarang), View (isinya sama dengan yg sekarang), Database (isinya sama dengan yg sekarang), Help (isinya: Help dan About)

**Comment by alfanugraha** [comment]
https://github.com/alfanugraha/lumens_ui/commit/8244211f6431e3a443a2b7b0b8e0c92f7ad3b659#diff-e5806712d56535ed40a5683e32468186
