### ISSUE TITLE
Common datasets for testing purpose

### ISSUE THREAD

**Issue by aekadinata** [alfanugraha/lumens_scripts#6]
Prepare testing datasets for LUMENS

**Comment by adwiputra** [comment]
Noted Mas Andree.. Thanks!

**Comment by adwiputra** [comment]
Teman-teman, @aekadinata, @alfanugraha, @arizkamufida 

Data utama untuk kebutuhan testing sudah diunggah pada icraf-nas6\LUMENS\#LUMENS_finaltesting\. Mohon masukannya apabila ada data yang belum lengkap atau isu-isu lainnya.

Sedikit catatan, data dibuat dengan resolusi dan proyeksi spasial yang beragam untuk menguji berbagai kemungkinan yang mungkin dialami oleh user ketika menginput data.

Salam,
Adrian dan @apandiwijaya
